
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 29 00:21:41 CST 2015
//----------------------------------------------------

package proyectocompi;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATERTHAN = 42;
  public static final int MULT = 37;
  public static final int ANY = 25;
  public static final int CHAR = 5;
  public static final int RET = 33;
  public static final int STR = 12;
  public static final int REPEND = 16;
  public static final int REP = 15;
  public static final int NOTEQUAL = 46;
  public static final int COND = 17;
  public static final int OPTEND = 24;
  public static final int MINUS = 36;
  public static final int SETEND = 22;
  public static final int YET = 19;
  public static final int AND = 39;
  public static final int CONDEND = 18;
  public static final int NIL = 34;
  public static final int LESSTHAN = 41;
  public static final int OR = 40;
  public static final int COMMA = 49;
  public static final int BOOL = 2;
  public static final int YETEND = 20;
  public static final int DIV = 38;
  public static final int TILEND = 28;
  public static final int NUM = 8;
  public static final int PLUS = 35;
  public static final int DIGIT = 3;
  public static final int ASSIGN = 14;
  public static final int MAIN = 29;
  public static final int ID = 7;
  public static final int PARIZQ = 47;
  public static final int EOF = 0;
  public static final int GREATEREQUALTHAN = 43;
  public static final int EQUAL = 45;
  public static final int ACTEND = 32;
  public static final int error = 1;
  public static final int SYM = 11;
  public static final int ANYEND = 26;
  public static final int MAINEND = 30;
  public static final int TIL = 27;
  public static final int BIN = 9;
  public static final int ACT = 31;
  public static final int LESSEQUALTHAN = 44;
  public static final int FLOAT = 4;
  public static final int END = 13;
  public static final int STRING = 6;
  public static final int OPT = 23;
  public static final int DEC = 10;
  public static final int PARDER = 48;
  public static final int SET = 21;
}

