
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150226 (SVN rev 63)
//----------------------------------------------------

package proyectocompi;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 16;
  public static final int PLUS = 12;
  public static final int DIGIT = 3;
  public static final int CHAR = 5;
  public static final int PARIZQ = 17;
  public static final int END = 11;
  public static final int PARDER = 18;
  public static final int ID = 7;
  public static final int NUM = 8;
  public static final int FLOAT = 4;
  public static final int EOF = 0;
  public static final int MULT = 14;
  public static final int DIV = 15;
  public static final int DEC = 9;
  public static final int MINUS = 13;
  public static final int error = 1;
  public static final int ASSIGN = 10;
  public static final int STR = 6;
  public static final int BOOL = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOL",
  "DIGIT",
  "FLOAT",
  "CHAR",
  "STR",
  "ID",
  "NUM",
  "DEC",
  "ASSIGN",
  "END",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "MOD",
  "PARIZQ",
  "PARDER"
  };
}

