/* The following code was generated by JFlex 1.6.0 */


package proyectocompi;

import java.util.ArrayList;
import javax.swing.JTextArea;
import java_cup.runtime.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.0
 * from the specification file <tt>src/proyectocompi/TieFlex.flex</tt>
 */
class TieLexer extends sym implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMMENTS = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\13\1\13\1\13\1\13\1\13\22\0\1\13\1\42\1\14"+
    "\1\45\1\0\1\37\1\0\1\12\1\46\1\47\1\36\1\34\1\44"+
    "\1\35\1\15\1\16\12\1\1\0\1\31\1\40\1\21\1\41\1\0"+
    "\1\43\32\20\1\0\1\0\1\0\1\0\1\20\1\0\1\7\1\24"+
    "\1\27\1\26\1\5\1\6\2\20\1\25\2\20\1\10\1\23\1\22"+
    "\1\33\1\32\1\20\1\3\1\11\1\2\1\4\3\20\1\30\1\20"+
    "\1\0\1\17\10\0\1\13\32\0\1\13\u15df\0\1\13\u097f\0\13\13"+
    "\35\0\1\13\1\13\5\0\1\13\57\0\1\13\u0fa0\0\1\13\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ud00f\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\5\4\1\1\1\5\1\1"+
    "\1\6\1\7\1\3\1\10\1\3\4\4\1\11\1\3"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\3\1\20"+
    "\1\21\1\1\1\22\1\23\2\5\1\0\12\4\2\0"+
    "\1\24\6\0\1\4\1\25\6\4\1\26\2\4\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\4\1\35\1\36"+
    "\1\37\1\40\1\4\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\7\0\1\50\1\51\1\52\1\53\1\54"+
    "\1\55\1\56\1\57\1\34\1\60\1\61\1\62\1\63"+
    "\1\64\1\65\1\66\1\67";

  private static int [] zzUnpackAction() {
    int [] result = new int[112];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\170\0\240\0\310\0\360\0\u0118"+
    "\0\u0140\0\u0168\0\u0190\0\u01b8\0\u01e0\0\120\0\u0208\0\u0230"+
    "\0\u0258\0\u0280\0\u02a8\0\u02d0\0\u02f8\0\u0320\0\120\0\u0348"+
    "\0\120\0\120\0\120\0\120\0\u0370\0\u0398\0\u03c0\0\120"+
    "\0\120\0\u03e8\0\120\0\120\0\120\0\u0410\0\u0438\0\u0460"+
    "\0\u0488\0\u04b0\0\u04d8\0\u0500\0\u0528\0\u0550\0\u0578\0\u05a0"+
    "\0\u05c8\0\u05f0\0\u01e0\0\u01e0\0\u0618\0\u0640\0\u0668\0\u0690"+
    "\0\u06b8\0\u06e0\0\u0230\0\120\0\u0708\0\u0730\0\u0758\0\u0780"+
    "\0\u07a8\0\u07d0\0\360\0\u07f8\0\u0820\0\120\0\120\0\120"+
    "\0\120\0\120\0\u0848\0\u0870\0\360\0\360\0\360\0\360"+
    "\0\u0898\0\360\0\360\0\360\0\360\0\360\0\360\0\120"+
    "\0\u08c0\0\u08e8\0\u0910\0\u0938\0\u0960\0\u0988\0\u09b0\0\360"+
    "\0\360\0\360\0\360\0\360\0\360\0\360\0\360\0\120"+
    "\0\360\0\120\0\120\0\120\0\120\0\120\0\120\0\120";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[112];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\2\7\1\10\1\11\1\7"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\7"+
    "\1\21\1\22\1\7\1\23\1\7\1\24\1\25\1\26"+
    "\1\27\1\7\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\13\45"+
    "\1\14\3\45\1\14\16\45\1\46\11\45\51\0\1\4"+
    "\13\0\1\47\33\0\2\7\1\50\6\7\5\0\2\7"+
    "\1\0\3\7\1\51\3\7\1\0\2\7\15\0\3\7"+
    "\1\52\1\53\4\7\5\0\2\7\1\0\7\7\1\0"+
    "\2\7\15\0\11\7\5\0\2\7\1\0\7\7\1\0"+
    "\2\7\15\0\6\7\1\54\2\7\5\0\2\7\1\0"+
    "\7\7\1\0\2\7\15\0\11\7\5\0\2\7\1\0"+
    "\1\55\4\7\1\56\1\7\1\0\2\7\15\0\1\7"+
    "\1\57\2\7\1\60\4\7\5\0\2\7\1\0\6\7"+
    "\1\61\1\0\2\7\14\0\50\62\13\0\1\14\3\0"+
    "\1\14\30\0\14\63\1\64\33\63\2\0\1\65\1\66"+
    "\3\0\1\67\1\0\1\70\15\0\1\71\1\72\20\0"+
    "\11\7\1\0\1\14\3\0\1\73\1\7\1\0\7\7"+
    "\1\0\2\7\35\0\1\74\27\0\3\7\1\75\5\7"+
    "\5\0\2\7\1\0\3\7\1\76\3\7\1\0\2\7"+
    "\15\0\11\7\5\0\2\7\1\0\3\7\1\77\3\7"+
    "\1\0\2\7\15\0\4\7\1\100\4\7\5\0\2\7"+
    "\1\0\7\7\1\0\2\7\15\0\11\7\5\0\2\7"+
    "\1\0\7\7\1\0\1\7\1\101\15\0\4\7\1\102"+
    "\4\7\5\0\2\7\1\0\7\7\1\0\2\7\15\0"+
    "\2\7\1\103\1\104\5\7\5\0\2\7\1\0\7\7"+
    "\1\0\1\105\1\7\35\0\1\106\47\0\1\107\47\0"+
    "\1\110\64\0\1\111\56\0\1\112\3\0\1\113\13\0"+
    "\2\113\32\0\3\7\1\114\5\7\5\0\2\7\1\0"+
    "\7\7\1\0\2\7\15\0\7\7\1\115\1\7\5\0"+
    "\2\7\1\0\7\7\1\0\2\7\15\0\11\7\5\0"+
    "\2\7\1\0\1\116\6\7\1\0\2\7\15\0\1\7"+
    "\1\117\7\7\5\0\2\7\1\0\7\7\1\0\1\120"+
    "\1\7\15\0\7\7\1\121\1\7\5\0\2\7\1\0"+
    "\7\7\1\0\2\7\15\0\11\7\5\0\2\7\1\0"+
    "\4\7\1\122\1\7\1\123\1\0\2\7\15\0\1\7"+
    "\1\124\7\7\5\0\2\7\1\0\7\7\1\0\2\7"+
    "\15\0\2\7\1\125\6\7\5\0\2\7\1\0\7\7"+
    "\1\0\2\7\15\0\1\7\1\126\7\7\5\0\2\7"+
    "\1\0\7\7\1\0\2\7\15\0\11\7\5\0\2\7"+
    "\1\0\1\7\1\127\5\7\1\0\2\7\26\0\1\130"+
    "\62\0\1\131\26\0\1\132\1\133\71\0\1\134\25\0"+
    "\1\135\75\0\1\136\21\0\1\137\43\0\11\7\5\0"+
    "\2\7\1\0\1\7\1\140\5\7\1\0\2\7\15\0"+
    "\7\7\1\141\1\7\5\0\2\7\1\0\7\7\1\0"+
    "\2\7\15\0\11\7\5\0\2\7\1\0\1\142\6\7"+
    "\1\0\2\7\15\0\11\7\5\0\2\7\1\0\5\7"+
    "\1\143\1\7\1\0\2\7\15\0\11\7\5\0\2\7"+
    "\1\0\1\144\6\7\1\0\2\7\15\0\1\7\1\145"+
    "\7\7\5\0\2\7\1\0\7\7\1\0\2\7\15\0"+
    "\1\7\1\146\7\7\5\0\2\7\1\0\7\7\1\0"+
    "\2\7\15\0\1\7\1\147\7\7\5\0\2\7\1\0"+
    "\7\7\1\0\2\7\15\0\1\150\13\0\2\150\32\0"+
    "\4\7\1\151\4\7\5\0\2\7\1\0\7\7\1\0"+
    "\2\7\15\0\10\7\1\114\5\0\2\7\1\0\7\7"+
    "\1\0\2\7\24\0\1\152\61\0\1\153\57\0\1\154"+
    "\17\0\1\155\47\0\1\156\67\0\1\157\27\0\1\160"+
    "\45\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2520];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\12\1\1\11\10\1\1\11\1\1\4\11"+
    "\3\1\2\11\1\1\3\11\1\1\1\0\12\1\2\0"+
    "\1\1\6\0\1\1\1\11\11\1\5\11\15\1\1\11"+
    "\7\0\10\1\1\11\1\1\7\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[112];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public static JTextArea outputArea;
    public static ArrayList<String> lexErrors = new ArrayList<String>();

    public void printOutput(String outputLine){
            if(outputArea != null){
                    outputArea.append(outputLine + "\n");
            } 
            lexErrors.add(outputLine);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  TieLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 192) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;           
    int totalRead = 0;
    while (totalRead < requested) {
      int numRead = zzReader.read(zzBuffer, zzEndRead + totalRead, requested - totalRead);
      if (numRead == -1) {
        break;
      }
      totalRead += numRead;
    }

    if (totalRead > 0) {
      zzEndRead += totalRead;
      if (totalRead == requested) { /* possibly more input available */
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      return false;
    }

    // totalRead = 0: End of stream
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { this.printOutput("> Unknown Token: '"+yytext()+"' in Line "+Integer.toString(yyline)+" Column "+Integer.toString(yycolumn) );
          }
        case 56: break;
        case 2: 
          { return new Symbol( sym.DIGIT, Integer.parseInt(yytext()) );
          }
        case 57: break;
        case 3: 
          { return new Symbol(sym.NOT);
          }
        case 58: break;
        case 4: 
          { return new Symbol(sym.ID, yytext());
          }
        case 59: break;
        case 5: 
          { 
          }
        case 60: break;
        case 6: 
          { return new Symbol(sym.DOT);
          }
        case 61: break;
        case 7: 
          { return new Symbol(sym.DIV);
          }
        case 62: break;
        case 8: 
          { return new Symbol(sym.ASSIGN);
          }
        case 63: break;
        case 9: 
          { return new Symbol(sym.END);
          }
        case 64: break;
        case 10: 
          { return new Symbol(sym.PLUS);
          }
        case 65: break;
        case 11: 
          { return new Symbol(sym.MINUS);
          }
        case 66: break;
        case 12: 
          { return new Symbol(sym.MULT);
          }
        case 67: break;
        case 13: 
          { return new Symbol(sym.MOD);
          }
        case 68: break;
        case 14: 
          { return new Symbol(sym.LESSTHAN);
          }
        case 69: break;
        case 15: 
          { return new Symbol(sym.GREATERTHAN);
          }
        case 70: break;
        case 16: 
          { return new Symbol(sym.THIS);
          }
        case 71: break;
        case 17: 
          { return new Symbol(sym.COMMA);
          }
        case 72: break;
        case 18: 
          { return new Symbol(sym.PARIZQ);
          }
        case 73: break;
        case 19: 
          { return new Symbol(sym.PARDER);
          }
        case 74: break;
        case 20: 
          { return new Symbol( sym.STRING, new String(yytext()) );
          }
        case 75: break;
        case 21: 
          { return new Symbol(sym.EQUAL);
          }
        case 76: break;
        case 22: 
          { return new Symbol(sym.OR);
          }
        case 77: break;
        case 23: 
          { return new Symbol(sym.LESSEQUALTHAN);
          }
        case 78: break;
        case 24: 
          { return new Symbol(sym.GREATEREQUALTHAN);
          }
        case 79: break;
        case 25: 
          { return new Symbol(sym.NOTEQUAL);
          }
        case 80: break;
        case 26: 
          { yybegin(COMMENTS);
          }
        case 81: break;
        case 27: 
          { yybegin(YYINITIAL);
          }
        case 82: break;
        case 28: 
          { return new Symbol( sym.FLOAT, new Float(yytext()) );
          }
        case 83: break;
        case 29: 
          { return new Symbol(sym.TIL);
          }
        case 84: break;
        case 30: 
          { return new Symbol(sym.MAIN);
          }
        case 85: break;
        case 31: 
          { return new Symbol(sym.RET);
          }
        case 86: break;
        case 32: 
          { return new Symbol(sym.REP);
          }
        case 87: break;
        case 33: 
          { return new Symbol(sym.AND);
          }
        case 88: break;
        case 34: 
          { return new Symbol(sym.ANY);
          }
        case 89: break;
        case 35: 
          { return new Symbol(sym.ACT);
          }
        case 90: break;
        case 36: 
          { return new Symbol(sym.STR);
          }
        case 91: break;
        case 37: 
          { return new Symbol(sym.SET);
          }
        case 92: break;
        case 38: 
          { return new Symbol(sym.SYM);
          }
        case 93: break;
        case 39: 
          { return new Symbol( sym.CHAR, yytext().charAt(0) );
          }
        case 94: break;
        case 40: 
          { return new Symbol(sym.NUM);
          }
        case 95: break;
        case 41: 
          { return new Symbol(sym.NIL);
          }
        case 96: break;
        case 42: 
          { return new Symbol(sym.BIN);
          }
        case 97: break;
        case 43: 
          { return new Symbol(sym.DEC);
          }
        case 98: break;
        case 44: 
          { return new Symbol(sym.COND);
          }
        case 99: break;
        case 45: 
          { return new Symbol(sym.YET);
          }
        case 100: break;
        case 46: 
          { return new Symbol(sym.OUT);
          }
        case 101: break;
        case 47: 
          { return new Symbol(sym.OPT);
          }
        case 102: break;
        case 48: 
          { return new Symbol( sym.BOOL, new Boolean(yytext()) );
          }
        case 103: break;
        case 49: 
          { return new Symbol(sym.TILEND);
          }
        case 104: break;
        case 50: 
          { return new Symbol(sym.MAINEND);
          }
        case 105: break;
        case 51: 
          { return new Symbol(sym.REPEND);
          }
        case 106: break;
        case 52: 
          { return new Symbol(sym.ACTEND);
          }
        case 107: break;
        case 53: 
          { return new Symbol(sym.SETEND);
          }
        case 108: break;
        case 54: 
          { return new Symbol(sym.CONDEND);
          }
        case 109: break;
        case 55: 
          { return new Symbol(sym.YETEND);
          }
        case 110: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {     return new Symbol(sym.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
